"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _chat_widget_skeleton from './chat-widget-skeleton.bones.json'

configureBoneyard({"color":"rgba(255, 255, 255, 0.05)","darkColor":"rgba(255, 255, 255, 0.05)","shimmerColor":"rgba(255, 255, 255, 0.1)","darkShimmerColor":"rgba(255, 255, 255, 0.1)"})

registerBones({
  "chat-widget-skeleton": _chat_widget_skeleton,
})
